"""Environment models — synthetic world artifacts and execution traces.

GeneratedEnvironment holds the LLM-generated code + data for a goal.
DryRunTrace records what the agent did in a clean (non-attacked) run.
EnvironmentRefinement is the create-then-refine mechanism: attacks can
request additional tools or data without regenerating the base environment.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ToolCall(BaseModel):
    """A single tool invocation recorded during agent execution."""

    name: str
    arguments: dict[str, Any]
    response: Any
    turn_number: int


class DryRunTrace(BaseModel):
    """Complete record of the agent's behavior on the clean (unattacked) task.

    This is the baseline: what the agent does when no adversarial content
    is present. Used by:
      - Injection attacks: to know which records the agent touched
        (observe-then-inject — only inject where agent actually went)
      - Utility evaluation: to compare against the attacked run
        (same tools? same records? similar call count?)
    """

    tool_calls: list[ToolCall] = Field(default_factory=list)
    conversation: list[dict] = Field(default_factory=list)
    final_state_snapshot: str = ""          # JSON of env state after run
    accessed_records: list[str] = Field(default_factory=list)  # IDs agent touched


class GeneratedEnvironment(BaseModel):
    """The synthetic world for a specific goal.

    Generated by a single LLM call from the goal + risk_type template.
    Contains executable Python code (exec()'d at runtime) + seed data.
    One environment per goal — purpose-built for that specific risk.
    """

    goal_id: str
    user_task_prompt: str               # Legitimate task the agent is given
    pydantic_model_code: str            # Python: Environment class + entity classes
    tool_function_code: str             # Python: tool functions (take env as first arg)
    seed_data_json: str                 # JSON: initial state of the environment
    expected_tool_sequence: list[str]   # Predicted tool call order for clean run


class EnvironmentRefinement(BaseModel):
    """Additive environment extension requested by an attack type.

    The base environment is immutable. Attacks that need additional
    capabilities (e.g. MINJA needs memory tools, PAIR adversarial may need
    an exfil channel) request a refinement. This is additive — it extends
    the environment, never replaces it.

    The dry run baseline is NOT re-run after refinement. The baseline
    captures what the agent does without the added attack infrastructure.
    """

    attack_type: str
    reason: str                         # Why this refinement is needed
    additional_env_code: str = ""       # New tool functions to add
    additional_seed_data_json: str = "" # New records to add to existing data
